FROM python:3.11-slim


# System deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app


# Install Python deps first for caching
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt


# Copy source
COPY api ./api
COPY data_pipeline ./data_pipeline
COPY model_pipeline ./model_pipeline
COPY trained_models ./trained_models
COPY version.txt .


ENV PORT=8080 \
    MODEL_LOCAL_PATH=trained_models/model-latest.joblib


EXPOSE 8080


CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8080"]